apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: collectds.collectdmon.collectd.org
spec:
  group: collectdmon.collectd.org
  names:
    kind: Collectd
    listKind: CollectdList
    plural: collectds
    singular: collectd
  scope: Namespaced
  subresources:
      status: {}
  validation:
    openAPIV3Schema:
      required:
        - spec
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            deploymentPlan:
              type: object
              properties:
                configname:
                  type: string
                  description: Collectd config filename
                image:
                  type: string
                  description: The image used for the collectd deployment
                size:
                  type: integer
                  minimum: 1
                  maximum: 1
                  description: The number of Daemonset pods to deploy
              required:
                - configname
        status:
          type: object
          required:
          - pods
          - conditions
          properties:
            revNumber:
              type: string
            pods:
              items:
                type: string
              type: array
            phase:
              type: string
            conditions:
              description: Conditions keeps most recent collectd conditions
              items:
                properties:
                  reason:
                    type: string
                  transitionTime:
                    format: date-time
                    type: object
                  type:
                    type: string
                required:
                - type
                type: object
              type: array
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
